### ISSUE TITLE
Feature Request: wav Support?

### ISSUE THREAD

**Issue by Leitftw** [andresch/trackfs#8]
Many of the files in my music library are .wav which would be great if possible. I'm not sure how difficult it would be, but .wav support would be nice.

**Comment by andresch** [comment]
I had thought about this already. Technically this should not be too complex, but would require some bigger refactoring in the code base. Will definitively look into it, but can't promise how fast I will be able deliver.

If you urgently need a solution, please also have a look at ffmpegfs and #4. ffmpegfs already supports wav & cue and in #4 I describe how you could wrap it into a docker container (until docker support is enabled directly in ffmpegfs)

**Comment by Leitftw** [comment]
Glad to hear it. But I think trackfs seems to be more suitable for music streaming server(for me maybe), I will wait and see, 
Thanks a lot!

**Comment by andresch** [comment]
I've just added a first version with support for .wav files and accompanying cuesheets. I don't have many wav files to test. Let me know if it works for you.

**Comment by Leitftw** [comment]
Everything seems work well for me. If there are any problems I will let you know, But I noticed that the embedded album art WAV file doesn't show up in the split FLAC files,it's not a big deal I juse let you know. And I thought you would split the wav into multiple wav files, is this transcoding?

**Comment by andresch** [comment]
Great to hear that it works for you!

Can you help me understand what you mean with "embedded album art" in WAV files. I'm no expert in WAV, but my understanding is that WAV files can't contain meta-data (no tags, no album art, no cue-sheets) and due to that my current implementation solely relies on accompanying album-art & cue-sheets that lie in the the same directory as the WAV file. 

That is also the reason why I do not only split the WAV files, but also re-encode the track as FLAC; otherwise I would not know where to store the metadata. 

But maybe my understanding of the WAV format is wrong and you can add all of that. If you could provide me some example WAV file with embedded meta-data / album-art, I'll see if I can support this.

**Comment by Leitftw** [comment]
Yes you are right about WAV meta-data please forget what I said. However, I found a problem that all my flac files doesn't exist at the mount point, FLAC+CUE and WAVE/Flac files with accompanying cuesheet are working properly. It was normal in the previous version.

**Comment by andresch** [comment]
This bug was a (unplanned) side effect of some of the refactorings for supporting WAV files (see gh-12). Is already fixed in the latest version
