### ISSUE TITLE
path /mnt/mdisc is mounted on / but it is not a shared mount

### ISSUE THREAD

**Issue by yyysuo** [andresch/trackfs#9]
docker run -d --name trackfs --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined -v /mnt/sdb2/test:/src:ro -v /mnt/mdisc:/dst:rshared andresch/trackfs --root-allowed

how can I get this problem fixed,thank you very much.

**Comment by andresch** [comment]
I do not really know what this error message is about. I doubt that this is a trackfs error message (at least noting that comes from my codebase) but rather coming from docker. At least I found some references to such an error message on various docker related projects.

I would try the following:

- remove the ":rshared" property from the /dst mount point and retry. As long as you run as root, it should not make a difference
- assuming /mnt/mdisc is already a mount point in your system (independent of docker)

   - try in a different, regular (empty) directly to see if the problem is really related to this mount point
   - play around with the mount options of /mnt/disc

As said I'm only guessing. Can't guarantee any of this will get this sorted out. But still hope it helps.

**Comment by yyysuo** [comment]
> I do not really know what this error message is about. I doubt that this is a trackfs error message (at least noting that comes from my codebase) but rather coming from docker. At least I found some references to such an error message on various docker related projects.
> 
> I would try the following:
> 
> * remove the ":rshared" property from the /dst mount point and retry. As long as you run as root, it should not make a difference
> * assuming /mnt/mdisc is already a mount point in your system (independent of docker)
>   
>   * try in a different, regular (empty) directly to see if the problem is really related to this mount point
>   * play around with the mount options of /mnt/disc
> 
> As said I'm only guessing. Can't guarantee any of this will get this sorted out. But still hope it helps.

thank you very much,the container can be created after remove the rshare parameter,but no split tracks show in the mount folder, I will keep studying.

**Comment by yyysuo** [comment]
without rshare parameter,the container can be created successfully, but no file show up in the folder of host, but in the dst folder of container,I can see splited tracks. just feed back for you information.

**Comment by andresch** [comment]
You are right. I mixed up the `user_allow_other` option of FUSE that is required when you want other user to access a fuse mountpoint with the mount option `shared`. The latter is required so that the mount point created by FUSE inside the '/dst' mount point of the docker container is also visible outside of the docker container.

Found a good reference on [kernel.org](https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt)

Did you find a way for you to run?

Based on the linked doc, I would guess you have to mount your /mnt/disk with --make-shared

Please let me know if you found a solution; would like to add this to the troubleshooting section.
